export {
    Angle,
    DEFAULT_TOLERANCE,
    FULL_TURN,
    GeometryResult,
    HALF_TURN,
    Interval,
    MATH_EPSILON,
    RIGHT_ANGLE,
    Scalar,
    Tolerance,
    type GeometryResultStatus,
} from './value';
export {
    Matrix3,
    Matrix4,
    Quaternion,
    Vec2,
    Vec3,
    Vec4,
    type Vector2,
    type Vector3,
    type Vector4,
} from './linear';
export { Coord2, Coord3 } from './coordinate';
export {
    Arc2,
    BBox2,
    BSpline2,
    Bezier2,
    Circle2,
    CurveParameter,
    Ellipse2,
    EllipticalArc2,
    Line2,
    LineSegment2,
    Nurbs2,
    ParameterDomain,
    Polygon2,
    Polyline2,
    Curve2,
    type BoundedCurve2,
    type CurveSamplingOptions,
    type PolygonOrientation,
    type PolygonPointClassification,
} from './geometry-2d';
export {
    BBox3,
    Line3,
    LineSegment3,
    OBB3,
    Plane3,
    Ray3,
    Sphere3,
    type Triangle3,
} from './geometry-3d';
export {
    Classification,
    Containment,
    Distance,
    Intersection,
    Measurement,
    Projection,
    type ClassificationResult,
    type ClassificationStatus,
    type ClosestPointResult,
    type ContainmentResult,
    type DistanceResult,
    type IntersectionResult,
    type MeasurementResult,
    type ProjectionResult,
    type SegmentSegment2Intersection,
    type SegmentSegment2OverlapIntersection,
    type SegmentSegment2PointIntersection,
} from './query';
export { BoundsApproximation, CurveSampler, PolylineApproximation } from './approximation';
